word=("hello world")
print(word[:  ])
print("goodbye "* 10)
print(word.lower())
print(word.upper())
print(' '.join(reversed(word)))
print(word.rstrip())
print("HELLO" + " WORD" + " 2")
print(word.isalnum())
print(",".join(reversed(word)))
tuple=(3,5,8,2,4,)
print(min(tuple))
print(max(tuple))
print(sorted(tuple))
print(len(tuple))
print(sum(tuple))
companies=["maltinea","pepsi","cocacola"]
print(companies.insert(2,"fanta"))